{% set version = "1.0.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-alakazam
  version: {{ version|replace("-", "_") }}

source:
  fn: alakazam_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/alakazam_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/alakazam/alakazam_{{ version }}.tar.gz
  sha256: 0eb46130b24f2999b07becaa95d1ea9f026e6d87d512eefde27a3c814c7f402d

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, rmarkdown, testthat
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-rcpp >=0.12.12
    - r-ape
    - r-dplyr >=0.8.1
    - r-ggplot2 >=2.0.0
    - r-igraph >=1.0.0
    - r-lazyeval
    - r-progress
    - r-readr
    - r-rlang
    - r-scales
    - r-seqinr
    - r-stringi
    - r-tibble
    - r-tidyr
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-matrix
    - r-rcpp >=0.12.12
    - r-ape
    - r-dplyr >=0.8.1
    - r-ggplot2 >=2.0.0
    - r-igraph >=1.0.0
    - r-lazyeval
    - r-progress
    - r-readr
    - r-rlang
    - r-scales
    - r-seqinr
    - r-stringi
    - r-tibble
    - r-tidyr

test:
  commands:
    - $R -e "library('alakazam')"           # [not win]
    - "\"%R%\" -e \"library('alakazam')\""  # [win]

about:
  home: http://alakazam.readthedocs.org
  license: AGPL-3.0-only
  summary: 'Provides methods for high-throughput adaptive immune  receptor repertoire sequencing (AIRR-Seq; Rep-Seq) analysis. In  particular, immunoglobulin (Ig) sequence lineage reconstruction,  lineage topology analysis, diversity profiling, amino acid property  analysis and gene usage. Citations:  Gupta and Vander Heiden,
    et al (2017) <doi:10.1093/bioinformatics/btv359>, Stern, Yaari and Vander Heiden, et al (2014) <doi:10.1126/scitranslmed.3008879>.'
  license_family: CC

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/AGPL-3
extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
