{% set version = "0.3.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-alakazam
  version: {{ version|replace("-", "_") }}

source:
  fn: alakazam_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/alakazam_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/alakazam/alakazam_{{ version }}.tar.gz
  sha256: 6f891805fdbaad0789358b55d65ed83e3a480813a67fe7878c575e554eadeac9

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, rmarkdown, testthat
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-rcpp >=0.12.12
    - r-ape
    - r-dplyr >=0.8.1
    - r-ggplot2 >=2.0.0
    - r-igraph >=1.0.0
    - r-lazyeval
    - r-progress
    - r-readr
    - r-rlang
    - r-scales
    - r-seqinr
    - r-stringi
    - r-tibble
    - r-tidyr
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-matrix
    - r-rcpp >=0.12.12
    - r-ape
    - r-dplyr >=0.8.1
    - r-ggplot2 >=2.0.0
    - r-igraph >=1.0.0
    - r-lazyeval
    - r-progress
    - r-readr
    - r-rlang
    - r-scales
    - r-seqinr
    - r-stringi
    - r-tibble
    - r-tidyr

test:
  commands:
    - $R -e "library('alakazam')"           # [not win]
    - "\"%R%\" -e \"library('alakazam')\""  # [win]

about:
  home: http://alakazam.readthedocs.org
  license: CC BY-SA 4.0
  summary: 'Provides methods for high-throughput adaptive immune  receptor repertoire sequencing
    (AIRR-Seq; Rep-Seq) analysis. In  particular, immunoglobulin (Ig) sequence lineage
    reconstruction,  lineage topology analysis, diversity profiling, amino acid property  analysis
    and gene usage. Citations:  Gupta and Vander Heiden, et al (2017) <doi:10.1093/bioinformatics/btv359>,
    Stern, Yaari and Vander Heiden, et al (2014) <doi:10.1126/scitranslmed.3008879>.'
  license_family: CC

extra:
   recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
